### ISSUE TITLE
Confusion about interpretation of results

### ISSUE THREAD

**Issue by vegetableyu** [YingZhou001/Immuannot#2]
Hi Ying,
Could I ask if there might be a possibility to write a document explaining the results in the future? I ran the example you provided, but I’m having trouble understanding the resulting files.
Best,
Yu

**Comment by YingZhou001** [comment]
Hi Yu,

Thanks for your suggestion. Could you specify which part is not clear? It is a gtf format and I would assume user needs to read the manuscript for further understanding.

Best,
Ying

**Comment by hangsuUNC** [comment]
Hi Ying,

Following up this question, I had trouble understanding the gtf file as well. When running the test example, I got an empty gtf file with the following:

```## format: gtf
## date: 2024-03-06
## gene (copy num = 0): HLA-A,HLA-B,HLA-C,HLA-DMA,HLA-DMB,HLA-DOA,HLA-DOB,HLA-DPA1,HLA-DPA2,HLA-DPB1,HLA-DPB2,HLA-DQA1,HLA-DQA2,HLA-DQB1,HLA-DQB2,HLA-DRA,HLA-DRB1,HLA-DRB2,HLA-DRB3,HLA-DRB4,HLA-DRB5,HLA-DRB6,HLA-DRB7,HLA-DRB8,HLA-DRB9,HLA-E,HLA-F,HLA-G,HLA-HFE,HLA-H,HLA-J,HLA-K,HLA-L,HLA-N,HLA-P,HLA-S,HLA-T,HLA-U,HLA-V,HLA-W,HLA-Y,KIR2DL1,KIR2DL2,KIR2DL3,KIR2DL4,KIR2DL5A,KIR2DL5B,KIR2DP1,KIR2DS1,KIR2DS2,KIR2DS3,KIR2DS4,KIR2DS5,KIR3DL1,KIR3DL2,KIR3DL3,KIR3DP1,KIR3DS1,MICA,MICB,TAP1,TAP2,C4A,C4B,C4X```

I have the same thing when running my own sample. Why the program provide empty output? Is there any suggestions for this?

Thanks,

Hang

**Comment by YingZhou001** [comment]
Any screen output?

**Comment by hangsuUNC** [comment]
Here it is:
<img width="563" alt="image" src="https://github.com/YingZhou001/Immuannot/assets/129195112/2bc3b96c-cee3-482a-838e-62d833b039b0">

**Comment by ydottie** [comment]
Hi, I am also having trouble interpreting the output gtf. For our study we need the HLA allele calls, but not the detailed annotation information. How do I find the HLA allele calls in the output gtf files? 

Thank you for your help. 
Dottie

**Comment by ydottie** [comment]
Hi Ying,
Thank you for the help! My confusion is that for some loci, there appear to be more than 2 allele calls. For instance, I filtered the gtf file for all the lines containing 'consensus "HLA-A..."'. It looks like there are >2 calls. Am I looking at the correct place? Which 2 alleles should I select?

Best
Dottie

<img width="1032" alt="截屏2024-04-07 下午5 45 01" src="https://github.com/YingZhou001/Immuannot/assets/89946726/3f777f1b-1831-4775-bc3a-6a6d986891c7">

**Comment by YingZhou001** [comment]
It is weird, what is your input? does it include multiple individuals?
You may also need to look at the contig names at the first column.
