### ISSUE TITLE
Incomplete GTF information

### ISSUE THREAD

**Issue by xuxingyubio** [YingZhou001/Immuannot#4]
Why is it that although DRB1 can be aligned 100%, the information for exon1 and exon2 is not in the GTF file?
<img width="1104" alt="图片1" src="https://github.com/YingZhou001/Immuannot/assets/94224642/7f6a7979-6720-4d7e-b59e-7836e131761f">

**Comment by YingZhou001** [comment]
Could you try to use grep "HLA-DRB1" to see what happened, or just look at the contig "ptg0000041" only?

**Comment by xuxingyubio** [comment]
Apologies for the confusion, I initially thought that the GTF file was arranged gene by gene. However, upon reviewing the file, it appears to be arranged according to the size of the fourth column. The results indeed include all the exons.

**Comment by YingZhou001** [comment]
No Worries, actually thanks for pointing this out. I think it is the software design problem. I will fix this and make it less confused in the next version.
