### ISSUE TITLE
Missed gene detection when there are many samples/contigs

### ISSUE THREAD

**Issue by ryought** [YingZhou001/Immuannot#7]
Thank you for making such a useful tool.
I noticed that some genes are missed when the number of samples (contigs) is large (e.g. 200 or more).
I think it may be necessary to set the upper limit of the number of secondary alignments to at least the number of samples with the minimap2 option -N.

**Comment by YingZhou001** [comment]
Thanks for reporting this to me!
Yes, the current version only supports one sample assembly for each run. I haven't tested different -N values yet. I may consider to include those options in the next version.
By the way, may I know what is your case in applying Immuannot? If you have multiple full length genomes, the best practice  I suppose is to separate them into each fa or fq file; but if you are looking at the MHC/KIR region, it should be very fast to extract each contig with seqtk.

**Comment by ryought** [comment]
Okay, thanks for your answer!
I want to compare the diversity of the gene regions between HPRC samples and my own samples. I will run the script for each sample individually.
