### ISSUE TITLE
searchTemplate.py script issue

### ISSUE THREAD

**Issue by vegetableyu** [YingZhou001/Immuannot#9]
Hi ying,
    These two segments of code:
        tmp = x0
        x0 = y0
        y0 = x0
    and
        tmp = x1
        x1 = y1
        y1 = x1
are confusing me. It seems like tmp is not serving any purpose, and the output will make x0=y0/y1=x1. I don’t quite understand the role of this code during mergeInterval. Can you please explain it ? Thank you for your help!
![image](https://github.com/user-attachments/assets/9b766800-8a15-4818-b819-86e22d91ca31)

**Comment by YingZhou001** [comment]
Sorry to get back to you lately. That should be a bug, thanks for reporting here

**Comment by yeeus** [comment]
> Sorry to get back to you lately. That should be a bug, thanks for reporting here.
> Should be fixed now.

Hi! I have used Immuannot to call HLA alleles. I'd like to know what this bug will cause? Would it have great effect on final results?

**Comment by YingZhou001** [comment]
I think the effect should be very minor since our evaluation showed pretty high consistency with other methods.
You may compare the difference between the early version (with this bug) and current version on some selected samples to see whether there is any significant difference in allele typing.

**Comment by vegetableyu** [comment]
Thank you so much for addressing and fixing the bug. Immuannot is an exceptional tool.
